### PR TITLE
adding input fields for custom screen size and validations

### PR DESCRIPTION
**Pull request by rahulchaudhary2244**
### **Description**
This PR adds a feature for passing custom screen sizes.

### **Related Issue**
https://github.com/suryanshsingh2001/mockly/issues/4

Closes # (issue)
https://github.com/suryanshsingh2001/mockly/issues/4

### **Changes Made**
1.) Implemented separate state variables to manage the dimensions of "customScreenSize" and "presetScreenSize". This allows for better tracking and control over the values for each screen size type.
2.) Updated the "screenSize" state based on the currently active tab, either "custom" or "preset". This ensures that the displayed screen size reflects the user's selection accurately.
3.) Added "handleCustomSizeChange" function to validate input for "customScreenSize". The validation allows only positive numerical values, ensuring data integrity and preventing invalid entries.

### **Type of Change**
_Select the type of change made with this pull request:_

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### **Screenshots (if applicable)**

https://github.com/user-attachments/assets/3c418488-1d7d-46c2-91ae-a8e62771812d

### **How Has This Been Tested?**
- _Manually tested on local environment_

### **Checklist**
_Check off the following items before submitting the pull request:_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
Hi @rahulchaudhary2244 ,

I noticed that changing the screen size to a very large value, such as `140000`, breaks the image rendering and the state becomes irreversible. To address this, we should set **maximum** and **minimum** limits for both height and width in the custom screen size input to prevent such issues.

### Task List:
- [ ] Define appropriate **maximum** (e.g., 2000px) and **minimum** (e.g., 100px) limits for height and width in the custom screen size input.
- [ ] Implement validation to ensure input values stay within the defined range.
- [ ] Display an error message when values outside the allowed range are entered.

Let me know your thoughts on this, and I can proceed with implementing the changes.


https://github.com/user-attachments/assets/c0dbd65f-7ed9-43c5-888f-3721b9ce79ff

**Comment by suryanshsingh2001** [comment]
@rahulchaudhary2244 
Just a quick reminder to pull the latest changes from the master repository to ensure you’re all up to date and avoid any potential merge conflicts as you work on new updates.

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
Hi @rahulchaudhary2244, there are some issues that we need to fix

- [ ] The screen size properties don't apply unless I press enter key. Change the state as the user types or if the input is blured
- [ ] I cannot set the resolution to 2k (2160 x 2160), increase the resolution to support atleast 2k.
- [ ] If there is an error, I cannot move to any other text input. Default behaviour should be on invalid values, set the value to default one.

https://github.com/user-attachments/assets/4a4062a1-91fe-4e4e-8597-59849bc99f20

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
Hey, everything good and working.
Only issue left.

- [x] Take the latest pull from `master` branch. Your branch in one commit behind right now.

**Comment by rahulchaudhary2244** [comment]
Hi @suryanshsingh2001 ,Thank you for reviewing the changes! I have implemented the following updates:

Added submit functionality for both the Enter key and the onBlur event.

- Increased the maximum resolution to 2K.

- When a user clicks on a different input field, the onBlur event is triggered. This will either display an error state or update the screenSize if the input is valid.

**Comment by suryanshsingh2001** [comment]
> Hey, everything good and working. Only issue left.
> 
> * [ ]  Take the latest pull from `master` branch. Your branch in one commit behind right now.
Please resolve this.

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
All good here. Just one change needed
Just take pull for latest changes done in `master` branch. Your branch is currenty behind one commit.

**Comment by rahulchaudhary2244** [comment]
Hi @suryanshsingh2001 , just rebased the branch., should be fine now

**Review by suryanshsingh2001 — APPROVED** [review]
All works well.

**Comment by suryanshsingh2001** [comment]
@rahulchaudhary2244 
Hi,
I wanted to take a moment to personally thank you for your valuable contributions. Your insights and solutions have truly shaped the way Mockly has progressed, and I’m incredibly grateful for your work.

If there are any other issues you’d like to explore or areas for further improvement, feel free to dive in. I’d love the opportunity to collaborate with you again in the future.

**Comment by suryanshsingh2001** [comment]
One more small request @rahulchaudhary2244 
Please make sure to star this to increase the overall reach of this repository to more open source traffic.

**Pull request merged**
