### PR TITLE
fixed small bug in the editor, added scrollable property

### LINKED ISSUE #36: [Bug] User  unable to see real time changes
### **Describe the bug**
User is unable to see real time changes which he will made to the image .It is bad user experience 
@suryanshsingh2001 assign me this under hacktoberfest

### **To Reproduce**
1. Go to '...' Try Now
2. Click on '...' Upload image
3. Scroll down to '...' scroll down and made changes user will not see what is the effect of changing parameter
4. See error     Unable too see changes real time

### **Expected behavior**
The side block of parameter should be scrollable and other should be fixed 

### **Screenshots**
Screenshot 2024-10-14 212318
Screenshot 2024-10-14 212329

### **Environment (please complete the following information):**
- **OS**: [e.g., Windows, macOS]
- **Browser**: [e.g., Chrome, Safari]
- **Version**: [e.g., 22]
- **Other relevant environment details** (e.g., Node version, database version)

### **Additional context**
_Add any other context about the problem here (e.g., error logs, stack traces)._

---

### **Optional Sections (if relevant):**

- **Priority ( High)**   
- **Is this issue blocking your progress?**  
- **Can you submit a PR to fix this?**     Yes

### PR DESCRIPTION
**Pull request by agnijeetsharma**
### **Description**
 I have added scrollable property to the left container and added CSS to make it good. I fixed CSS to make  it good .

### **Related Issue**
issue#36

Closes #36 

### **Changes Made**
_List out the specific changes made in this pull request:_
- _Changed X to Y..._
- _Refactored Z..._

### **Type of Change**
_Select the type of change made with this pull request:_

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)

### **Screenshots (if applicable)**

https://github.com/user-attachments/assets/471fdb44-cb99-4a7f-827c-592a232fba49

### **How Has This Been Tested?**
 I have added a video of the same.

- _Tested with unit tests_
- _Manually tested on local environment_

### **Checklist**
_Check off the following items before submitting the pull request:_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### **Additional Context**
@suryanshsingh2001 Kindly merge this PR under hacktoberfest if it is useful

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
Hey @agnijeetsharma, it seems the scrollable area is missing, and the spacing looks compressed. To resolve this, you can try adjusting the Tailwind CSS classes like `overflow-scroll` or `overflow-auto` for scroll functionality. Additionally, you could use the scrollable component from ShadCN UI for a more streamlined solution.

Here’s the link to the issue for reference:

https://github.com/user-attachments/assets/058d114c-1373-4443-8f6f-a03c9af9d6d4

**Comment by agnijeetsharma** [comment]
https://github.com/user-attachments/assets/6c7cf627-ea34-41ff-ae3b-36ef62feb64c

@suryanshsingh2001 Kindly check it and any changes you want let me know
Merge my PR under hacktoberfest-2024
Thanks

**Comment by suryanshsingh2001** [comment]
@agnijeetsharma Hey, the new scrollbar looks very shabby and of very different design language.
Please use [ScrollArea](https://ui.shadcn.com/docs/components/scroll-area) instead to handle this.

https://github.com/user-attachments/assets/11324558-c3f3-4a7e-8594-bd4a4d3067cc

**Comment by agnijeetsharma** [comment]
https://github.com/user-attachments/assets/73e91337-e131-4fa5-bfc8-d6d0877124ba

@suryanshsingh2001 If there is any issue kindly mention it

**Comment by suryanshsingh2001** [comment]
> bandicam.2024-10-15.23-12-18-280.mp4 
> @suryanshsingh2001 If there is any issue kindly mention it

Hey, it looks good. Just one thing, add some space for scrollbar.

**Comment by agnijeetsharma** [comment]
@suryanshsingh2001 Since the left container has a fixed width of 1/4, we cannot add too much padding; otherwise, it may cause an x-axis scrollbar to appear. Therefore, the current padding is perfect for this layout.

**Comment by suryanshsingh2001** [comment]
> @suryanshsingh2001 Since the left container has a fixed width of 1/4, we cannot add too much padding; otherwise, it may cause an x-axis scrollbar to appear. Therefore, the current padding is perfect for this layout.

Okay finish the refactoring. Will put this merge this in another branch.

**Comment by agnijeetsharma** [comment]
@suryanshsingh2001 You want to me give space for scroll-bar.

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
Please refactor Scroll Area component, it should in `components/ui` directory.
You can also use `npx shadcn@latest add scroll-area` to directly get the component and import it here.

**Comment by agnijeetsharma** [comment]
@suryanshsingh2001 Done

**Review by suryanshsingh2001 — APPROVED** [review]
Looks okay

**Pull request merged**
