### PR TITLE
Blog Post Written Content.

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
### **Changes Made**
Added info to Readme.md file.

### **Type of Change**
_Select the type of change made with this pull request:_

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

### **Checklist**
_Check off the following items before submitting the pull request:_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
Hey @Brijeshthummar02 
Thanks for the PR! The changes to the README look great. I recommend adding some visuals (like screenshots or diagrams) to make it even clearer. If you can, posting it on dev.to or Medium would help spread the word about Mockly. Alternatively, you can save it as a draft in blogs/[yourblog].md for future publishing.

**Comment by Brijeshthummar02** [comment]
Sounds great maybe i'll update visuals as soon as i will get time, would be grateful if merge current update readme file.

**Comment by suryanshsingh2001** [comment]
> Sounds great maybe i'll update visuals as soon as i will get time, would be grateful if you merge current update readme file.

Hey @Brijeshthummar02 , as mentioned in the issue #7, you need to submit an article link or you can save the article in the blog folder. This won't be added in the readme.
Please refer to the guidelines present in the issue.

**Comment by suryanshsingh2001** [comment]
This is duplicate PR, marking it as duplicate

**Pull request closed without merging**
