### PR TITLE
Feature/more download options

### PR DESCRIPTION
**Pull request by 0xkafkaa**
Added options for download. Implemented jpg/png/svg/pdf for download options. Used [jspdf](https://www.npmjs.com/package/jspdf) for downloading PDFs.

- [x] Add export options for JPG and PNG formats
- [x] Consider adding other formats like SVG or PDF for flexibility
- [x] Ensure that the quality of the exports is maintained across all formats
- [x] Add a dropdown or menu in the UI to allow users to select their preferred format before download

Let me know your comments.

Regards,
0xkafkaa.

### CODE REVIEW

**Review by suryanshsingh2001 — CHANGES_REQUESTED** [review]
The dropdown placement and appearance seems off. Everything else works perfectly

**Comment by suryanshsingh2001** [comment]
@0xkafkaa Hey, good job with download options. Here are some changes needed before we complete the PR.

- [ ] Use [Select Compoenent](https://ui.shadcn.com/docs/components/select) for making the dropdown component.

**Comment by 0xkafkaa** [comment]
@suryanshsingh2001 sure, will work and update

**Comment by 0xkafkaa** [comment]
Hey @suryanshsingh2001,

Added the dropdown component as discussed.
- [x] Use [Select Component](https://ui.shadcn.com/docs/components/select) for making the dropdown component.
- [x] Updated the reset handle to set image format to png. Can be customized from default settings.

Regards,
0xkafkaa.

**Comment by suryanshsingh2001** [comment]
Hey @0xkafkaam, there were some overflow issues on side menu. I have fixed that issue, you can now add the drop downdown component. Take a pull from `master` branch and add new changes.

**Comment by 0xkafkaa** [comment]
hey @suryanshsingh2001, let me if its ok.

**Review by suryanshsingh2001 — APPROVED** [review]
Good job. Everthing looks good here.

**Comment by suryanshsingh2001** [comment]
Hey @0xkafkaa, great job on this!
The `handleDownload` function is quite lengthy and could benefit from being refactored into the `lib` file for better maintainability. You can create another PR to handle this refactoring if you'd like!

**Comment by 0xkafkaa** [comment]
Ok. will look into it.

**Pull request merged**
