### PR TITLE
Feature/video

### PR DESCRIPTION
**Pull request by kvtemadden**
### **Description**
Added:
- Matching UI to image editor
- Brought up to date with main
- Screen recording ability
- Export video ability
- Added tabs to switch between editor/video editor (currently loses progress if switch tabs)

Ideas/To do:
- Consider brightness & trim when exporting
- Switch export to use `mp4` rather than `webm` (need an additional library i think)
- Add a context provider to the `editor` page with all state information for `editor` and `videoEditor`

### **Related Issue**
_If this PR is related to an open issue, please provide a link to the issue here._

Adds to # [9](https://github.com/suryanshsingh2001/mockly/issues/9)

### **Type of Change**
_Select the type of change made with this pull request:_

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### **Screenshots (if applicable)**
Screen Recording 2024-10-03 at 23 30 11

### **How Has This Been Tested?**
- _Manually tested on local environment_

### **Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### **Additional Context**
Hey - thought I'd have a go at this, feel free to close if you're not liking the changes, but thought some decent progress was made.

If you do like it, we could split the ideas up into new issues perhaps? Make it a bit more bitesize.

Let me know your thoughts!

### CODE REVIEW

**Comment by suryanshsingh2001** [comment]
Hey @kvtemadden 

Good job! This is solid progress, and I'm glad to see the work on the editor coming together. We can definitely iterate on some of the features later, but for now, let's make a few adjustments:

1. **Remove Tabs for Video and Image Editors**: We should eliminate the tabbed interface for switching between the image and video editors. Instead, let's move the video editor to a new dedicated page under `/video/beta`, leaving the image editor on its current page. This will keep the functionalities separate and reduce complexity.

2. **Reset Image Editor**: The image editor should be restored to the state it was in before the tabs were introduced. This way, no changes made during the integration of the video editor will affect the image editor.

3. **Additional Tasks**:
   - Remove the tabs used to switch between the image and video editors.
   - Create the `/video/beta` route for the video editor.

Once these are complete, we can look at improving other features or splitting the tasks into more manageable pieces.

Thanks again for the PR! Let me know if you need any further input.

---

### Task List
- [ ] Remove the tabs that switch between the image and video editors.
- [ ] Move the video editor to a separate page under `/video/beta`.
- [ ] Reset the image editor back to the way it was before the tabbed interface was introduced.

**Comment by kvtemadden** [comment]
Hey @suryanshsingh2001, sorry for the delay! I've just made those changes :)

**Comment by suryanshsingh2001** [comment]
@kvtemadden  Awesome work!. Please feel free to contribute more on this. This seems like a good idea to have quick video editor for those last minutes video demos. You can add issues for all of these. Everyone can contribute to these issues and make this project better.

- [ ] Consider brightness & trim when exporting
- [ ] Switch export to use mp4 rather than webm (need an additional library i think)

**Review by suryanshsingh2001 — APPROVED** [review]
Everything Looks Good!

**Pull request merged**
